[package]
name = "apmpkg"
version = "0.1.0-beta"
authors = ["kedap <dxhqezk@hi2.in>"]
edition = "2018"
description = "Un administrador de paquetes universal para linux como modelo: PKGBUILD"
readme = "README.md"
repository = "https://github.com/Kedap/apmpkg"
license = "Apache-2.0"
keywords = ["package-manager", "linux", "pkgbuild"]

[dependencies]
colored = "2"
clap = {version = "~2.27.0", features = ["yaml"]}
curl = "0.4.34"
toml = "0.5"
read_input = "0.8"